AWSTemplateFormatVersion: '2010-09-09'
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 10
Outputs:
  LandingApi:
    Description: API Gateway endpoint URL for Prod stage for landing function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/landing/
  LandingFunction:
    Description: Landing pageLambda Function ARN
    Value:
      Fn::GetAtt:
      - LandingFunction
      - Arn
  ProfileApi:
    Description: API Gateway endpoint URL for Prod stage for Profile page function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Profile/
  RestaurantApi:
    Description: API Gateway endpoint URL for Prod stage for Restaurant page function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Restaurant/
  RestaurantFunction:
    Description: Restaurant page Lambda Function ARN
    Value:
      Fn::GetAtt:
      - RestaurantFunction
      - Arn
  ReviewsApi:
    Description: API Gateway endpoint URL for Prod stage for reviews function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Reviews/
  ReviewsFunction:
    Description: Reviews Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ReviewsFunction
      - Arn
  SearchApi:
    Description: API Gateway endpoint URL for Prod stage for search functionality
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Search/
  SearchFunction:
    Description: Restaurant search Lambda Function ARN
    Value:
      Fn::GetAtt:
      - SearchFunction
      - Arn
Resources:
  AggregationFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/5d4ebc35093c19a4b87ba9ef916ba1b7
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /dbUpdate
          Type: Api
      Handler: aggregation.aggregationLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  CognitoUserGetFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/9999060e6384ff96350e7ffadb69b3ed
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /user/getByCognito
          Type: Api
      Handler: user.getUserByCognitoLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  CorsOptionsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/c6bb31f4348385a32abbaedb2de2b339
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Cors:
          Properties:
            Method: options
            Path: /{proxy+}
          Type: Api
      Handler: corsOptions.handler
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietAllFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/all
          Type: Api
      Handler: diet.getAllDietsLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietCreateAdminFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/createAdmin
          Type: Api
      Handler: diet.createDietAdminLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietCreateFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/create
          Type: Api
      Handler: diet.createDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietGroupsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/groups
          Type: Api
      Handler: diet.getFoodGroupsLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietPresetsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/presets
          Type: Api
      Handler: diet.getPresetDietsLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DietUpdateFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /diet/update
          Type: Api
      Handler: diet.updateDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  LandingFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/8922f020e58a65c856c23ca2a00b13aa
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /landing
          Type: Api
      Handler: landing.lambdaHandler
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  LocationCitiesFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/aaa25e3bb8921f30218ffd80767d4f9e
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /location/cities
          Type: Api
      Handler: location.getCitiesLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  LocationCountriesFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/aaa25e3bb8921f30218ffd80767d4f9e
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /location/countries
          Type: Api
      Handler: location.getCountriesLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnDietsCreateFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/c85452d235e3c9dd3883ba3e60833ba3
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownDiets/create
          Type: Api
      Handler: own_diet.createOwnDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnDietsDeleteFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/c85452d235e3c9dd3883ba3e60833ba3
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownDiets/delete
          Type: Api
      Handler: own_diet.deleteDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnDietsEditFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/c85452d235e3c9dd3883ba3e60833ba3
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownDiets/edit
          Type: Api
      Handler: own_diet.editOwnDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnDietsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/c85452d235e3c9dd3883ba3e60833ba3
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownDiets
          Type: Api
      Handler: own_diet.getOwnDietsLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnReviewsDeleteFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/e8fcce8912b2528dcb2a91b2e60a557c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownReviews/delete
          Type: Api
      Handler: own_review.deleteReviewLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnReviewsEditFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/e8fcce8912b2528dcb2a91b2e60a557c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownReviews/edit
          Type: Api
      Handler: own_review.editReviewLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  OwnReviewsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/e8fcce8912b2528dcb2a91b2e60a557c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /ownReviews
          Type: Api
      Handler: own_review.getOwnReviewsLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PostReviewFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/d215021a74a84059713c954da0ab20ef
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /postReview
          Type: Api
      Handler: reviews.postReviewLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ProfileEditFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/fd13731c101b32995e32debfd1824652
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /profile/edit
          Type: Api
      Handler: profile.editProfileLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ProfileFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/fd13731c101b32995e32debfd1824652
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /profile
          Type: Api
      Handler: profile.profileLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  RestaurantFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/3ff6d63c1bc48f1d672a12f2f93f7d54
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /restaurant
          Type: Api
      Handler: restaurant.lambdaHandler
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ReviewsFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/d215021a74a84059713c954da0ab20ef
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /reviews
          Type: Api
      Handler: reviews.lambdaHandler
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  SearchFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/b577ea18e24424fde220152e6ee45f0b
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /search
          Type: Api
      Handler: search.lambdaHandler
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  UserCreateFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/9999060e6384ff96350e7ffadb69b3ed
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /user/create
          Type: Api
      Handler: user.createUserLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  UserDeleteFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/9999060e6384ff96350e7ffadb69b3ed
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /user/delete
          Type: Api
      Handler: user.deleteUserLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  VoteDietFunction:
    Properties:
      CodeUri: s3://sipuliton-lambdas/28aaf163a1dc05db571f741135e9c11c
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        Landing:
          Properties:
            Method: get
            Path: /voteDiet
          Type: Api
      Handler: diet.voteDietLambda
      Role: arn:aws:iam::080857800046:role/lambda-vpc-role
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
