AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    sam-app

    Sample SAM Template for sam-app
    
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 3


Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: hello_world/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Events:
                HelloWorld:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /hello
                        Method: get

    LandingFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: landing/
          Handler: landing.lambdaHandler
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /landing
                      Method: get

    ProfileFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: profile/
          Handler: profile.profileLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /profile
                      Method: get

    ProfileEditFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: profile/
          Handler: profile.editProfileLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /profile/edit
                      Method: get

    UserCreateFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: user/
          Handler: user.createUserLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /user/create
                      Method: get

    UserDeleteFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: user/
          Handler: user.deleteUserLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /user/delete
                      Method: get

    OwnReviewsFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: own_review/
          Handler: own_review.getOwnReviewsLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /ownReviews
                      Method: get

    OwnReviewsEditFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: own_review/
          Handler: own_review.editReviewLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /ownReviews/edit
                      Method: get

    OwnReviewsDeleteFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: own_review/
          Handler: own_review.deleteReviewLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /ownReviews/delete
                      Method: get

    OwnDietsFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: own_diet/
          Handler: own_diet.getOwnDietsLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /ownDiets
                      Method: get

    OwnDietsDeleteFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: own_diet/
          Handler: own_diet.deleteDietLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /ownDiets/delete
                      Method: get

    LocationCitiesFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: location/
          Handler: location.getCitiesLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /location/cities
                      Method: get

    LocationCountriesFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: location/
          Handler: location.getCountriesLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /location/countries
                      Method: get

    DietPresetsFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: diet/
          Handler: diet.getPresetDietsLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /diet/presets
                      Method: get

    DietGroupsFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: diet/
          Handler: diet.getFoodGroupsLambda
          Runtime: nodejs8.10
          Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
              Variables:
                  PARAM1: VALUE
          Events:
              Landing:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /diet/groups
                      Method: get

Outputs:

    HelloWorldApi:
      Description: "API Gateway endpoint URL for Prod stage for Hello World function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
      Description: "Implicit IAM Role created for Hello World function"
      Value: !GetAtt HelloWorldFunctionRole.Arn

    LandingApi:
      Description: "API Gateway endpoint URL for Prod stage for landing function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/landing/"

    LandingFunction:
      Description: "Landing pageLambda Function ARN"
      Value: !GetAtt LandingFunction.Arn

    LandingFunctionIamRole:
      Description: "Implicit IAM Role created for Landing page function"
      Value: !GetAtt LandingFunctionRole.Arn

    ProfileApi:
      Description: "API Gateway endpoint URL for Prod stage for Profile page function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/Profile/"

    

